Update the manifest.toml main resources sources to tiki-26.0 which supports php8.1 to php8.2
YunoHost-Apps/tiki_ynh pull request #22
Opened 2023-09-06 13:15 UTC by rodriguezny

## Problem

- *Tiki 26.0 is released and runs under php8.1 to php8.2, but the resources.sources.main in manisfest.toml is not yet update to support the installation of or upgrade to tiki-26.0

## Solution

- Update the manifest.toml main resources.sources and resources.apt packages versions

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2023-09-06 14:01 UTC, ericgaspar commented
!testme

2023-09-06 14:14 UTC, marclaporte commented
@rodriguezny PHP 8.1 is well supported in Tiki 26x (we will fix any bug) but PHP 8.2 is Beta (We will fix everything for Tiki27 LTS): 
Ref: https://doc.tiki.org/Requirements#PHP_

2023-09-10 16:11 UTC, rodriguezny commented
Hello @ericgaspar ! 
I have a blocker in the "resources.apt" section as described bellow:
Tiki26.0 (resources.main) and tiki-24.4 (resources.lts) require diverging versions of php.

tiki26.0 (resources.main) requires php8.1, so I updated the packages value to handle this as it is said in the doc that "when packages contains some phpX.Y-foobar dependencies, this will automagically define a phpversion setting equal to X.Y which can therefore be used in app scripts ($phpversion) or templates (__PHPVERSION__)". With this the installation works and upgrade works perfectly, even the app when testing after installation.

But tiki24.4 requires php7.4. With the current configuration (packages set to php8.1) the installation of tiki_ynh also succeeds but there are errors warnings in the log due the php version which is no satisfiable.

So my question is that, is there a way to specify the packages to install depending with the type of installation (longterm or regular) ? I explored the yunohost doc but I found nothing that helped me. I also tried to use the syntax we use in the "resources.sources" section to specify where to get the app sources but it din't work.

Need help, thanks!

2023-09-10 16:34 UTC, ericgaspar commented
What about using something like this?
```
    [resources.apt]
    packages = "tesseract-ocr imagemagick mariadb-server"

    packages_from_raw_bash = """
            if [[ "$release_cycle" == "regular" ]]; then 
                echo "php8.1-bz2 php8.1-curl php8.1-gd php8.1-zip php8.1-mysql php8.1-xml php8.1-mbstring php8.1-intl"  
            else
                echo "php7.4-bz2 php7.4-curl php7.4-gd php7.4-zip php7.4-mysql php7.4-xml php7.4-mbstring php7.4-intl"
            fi
        """
```

2023-09-10 17:32 UTC, rodriguezny commented
Let me test it.

2023-09-10 18:17 UTC, rodriguezny commented
Thank you @ericgaspar,  it works like expected.

2023-09-10 19:08 UTC, ericgaspar requested changes

2023-09-10 19:08 UTC, ericgaspar commented on manifest.toml
> +version = "26.0~ynh2"
```suggestion
version = "26.0~ynh1"
```

2023-09-10 19:10 UTC, merged